### PR TITLE
Create apt_turlaCarbon.py

### PR DESCRIPTION
**Pull request by robbyFux**

### CODE REVIEW

**Comment by robbyFux** [comment]
No interest? Should I delete the signatures better?

**Comment by botherder** [comment]
They are quite complex, I need to test them and make sure they work fine against the latest Cuckoo developments. Unless you have done the same and can provide some samples to test them with.

**Comment by robbyFux** [comment]
test files on malwr.com are listed in the references

**Comment by robbyFux** [comment]
Why is Publishing So Slow? I still think some parts of publishing take way too long.

**Comment by botherder** [comment]
It could be faster, but I have the time that I have unfortunately.

**Pull request merged**
